
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: ClusterIP
  ports:
  - port: 8100
    targetPort: 80
  selector:
    app: demo-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-deploy
  template:
    metadata:
      labels:
        app: demo-deploy
    spec:
      containers:
      - name: demo-kubecon-container
        image: zanetworker/demo-webserver
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
#      hostNetwork: true
