apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkconnectivity-test-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: networkconnectivity-test-controller
    helm.sh/chart: networkconnectivity-test-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: networkconnectivity-test-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: networkconnectivity-test-controller
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: networkconnectivity-test-controller
      containers:
        - name: networkconnectivity-test-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - networkconnectivity-test-controller
          ports:
            - name: webhook-server
              containerPort: 9876
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              mountPath: /tmp/cert
      volumes:
        - name: cert
          secret:
            secretName: aws-webhooks
            defaultMode: 420
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-webhooks
  namespace: {{ .Release.Namespace }}
