---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkConnectivityTest
metadata:
  name: smokeping
spec:
    layer: "3"
    source:
      name: "kube-apiserver-kind-1-control-plane"
      namespace: "kube-system"
      container: ""
    destinations:
      - kind: pod
        namespace: default
        name: somepod
      - kind: pod
        namespace: default
        name: somepod2
      - kind: ip
        ip: "10.1.2.24"
      - kind: service
        namespace: default
        name: kubernetes

#      - kind: pod
#        name: "pod-name"
#        namespace: "pod-namespace"
#      - kind: pod
#        destinationSelector:
#          matchLabels:
#            release: "stable"
#      - kind: service
#        name: "pod-name"
#        namespace: "pod-namespace"
