---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkConnectivityTest
metadata:
  name: smokeping
spec:
    layer: "3"
    source:
      name: "kube-apiserver-docker-for-desktop"
      namespace: "kube-system"
      container: ""
    destinations:
      - kind: pod
        ip: "10.1.2.24"
#      - kind: pod
#        name: "pod-name"
#        namespace: "pod-namespace"
#      - kind: pod
#        destinationSelector:
#          matchLabels:
#            release: "stable"
#      - kind: service
#        name: "pod-name"
#        namespace: "pod-namespace"
