---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkConnectivityTest
metadata:
  name: smokeping
spec:
  tests: #TODO: layers can be implemented using a provider spec (different layer different object to serialize)
    - layer: "3"
      sources:
        - name: "pod-name"
          ip: "1.2.3.4"
      destinations:
        - name: "pod-name"
          ip: "1.2.3.5"
        - name: "pod-name2"
          ip: "1.2.3.2"
        - name: "pod-name3"
          ip: "1.2.3.3"
    - layer: "4"
      sources:
        - name: "pod--name" #must be pod name for the pod
          ip: "1.2.3.4"
      destinations:
        - name: "pod-service-name"
          ip: "1.2.3.5"
        - name: "pod-name2"
          ip: "1.2.3.2"
        - name: "pod-name3"
          ip: "1.2.3.3"