---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkConnectivityTest
metadata:
  name: smokeping
spec:
    layer: "3"
    sources:
      - name: "pod-name"
        ip: "1.2.3.4"
    destinations:
      - name: "pod-name"
        ip: "1.2.3.5"
      - name: "pod-name2"
        ip: "1.2.3.2"
      - name: "pod-name3"
        ip: "1.2.3.3"