---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkConnectivityTest
metadata:
  name: port-test
spec:
  layer: "4"
  source:
    name: "demo-pod-1"
    namespace: "default"
    container: ""
  destinations:
    - kind: service
      namespace: default
      name: demo-service
      port: "8100"
