---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkConnectivityTest
metadata:
  name: smokeping
spec:
  layer: "3"
  source:
    name: "demo-pod-1"
    namespace: "default"
    container: ""
  destinations:
    - kind: pod
      name: demo-pod-2
      namespace: default
    - kind: ip
      ip: "8.8.8.8"
    - kind: service
      namespace: default
      name: demo-service
