---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkTrafficShaper
metadata:
  name: inject-loss
spec:
  targets:
#    - kind: pod
#      namespace: default
#      name: demo-deploy-7dcb99b576-lrwvg
#      configuration:
#        type: loss
#        device: eth0
#        value: 100%
    - kind: selector
      namespace: default
      targetSelector:
        matchLabels:
          app: demo-deploy
      configuration:
        type: loss
        device: eth0
        value: 100%
