---
apiVersion: networkmachinery.io/v1alpha1
kind: NetworkMonitor
metadata:
  name: sflow-monitor
spec:
  monitoringEndpoint:
    ip: "10.0.0.10"
    port: "8008"
  flows:
    - name: "elephant-flow"
      keys: "ipsource,ipdestination,tcpsourceport,tcpdestinationport" #https://sflow-rt.com/define_flow.php#keys
      value: "frames"
      log: "true"
#      filter: "sourcegroup=external&destinationgroup=internal"
#      flowStart: false
#      activeTimeout: 60
  thresholds:
    - name: "elephant-flow"
      metric: tcp
      value: "30"
      flowName: "elephant-flow"
      byFlow: "true"
  eventsConfig:
    maxEvents: "5"
    timeout: "60"
